name       : scrcpy
version    : '1.18'
release    : 13
source     :
    - https://github.com/Genymobile/scrcpy/archive/v1.18.tar.gz : 2995d74409e9a486e4f69d0f623299ebf615d9427d8e974dfd82355538a313e9
    - https://github.com/Genymobile/scrcpy/releases/download/v1.18/scrcpy-server-v1.18 : 641c5c6beda9399dfae72d116f5ff43b5ed1059d871c9ebc3f47610fd33c51a3
license    : Apache-2.0
component  : network.util
summary    : Display and control your Android device
description: |
    This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(sdl2)
rundeps    :
    - android-tools
setup      : |
    %meson_configure --buildtype release --strip -Dportable=false -Dprebuilt_server="$sources/scrcpy-server-v$version" -Db_lto=true
build      : |
    %ninja_build
install    : |
    %ninja_install
