name       : scrcpy
version    : 1.9
release    : 2
source     :
    - https://github.com/Genymobile/scrcpy/archive/v1.9.tar.gz : 905fe62e2825310eeb77187f8974763c3ae2f08ca1f649bcaf4721f1fd14a764
license    : Apache-2.0
component  : network.util
summary    : Display and control your Android device
description: |
    This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(sdl2)
    - openjdk-8
rundeps    :
    - android-tools
setup      : |
    %patch -p1 < $pkgfiles/fix_build.patch
    %meson_configure --buildtype release --strip -Dportable=false -Dprebuilt_server="$pkgfiles/scrcpy-server-v1.9.jar" -Db_lto=true
build      : |
    %ninja_build
install    : |
    %ninja_install
