name       : scrcpy
version    : 1.12.1
release    : 7
source     :
    - https://github.com/Genymobile/scrcpy/archive/v1.12.1.tar.gz : 7692664e1bd703421eb9659cc9956d9f0ac64eb14abddab7b2ade37625f0243d
license    : Apache-2.0
component  : network.util
summary    : Display and control your Android device
description: |
    This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(sdl2)
    - openjdk-8
rundeps    :
    - android-tools
setup      : |
    %meson_configure --buildtype release --strip -Dportable=false -Dprebuilt_server="$pkgfiles/scrcpy-server-v$version" -Db_lto=true
build      : |
    %ninja_build
install    : |
    %ninja_install
