name       : scrcpy
version    : '1.20'
release    : 15
source     :
    - https://github.com/Genymobile/scrcpy/archive/v1.20.tar.gz : 0c667e7de043a67a740be99d3f236a7aa4107ff62c408e7c462f4fe291f045a7
    - https://github.com/Genymobile/scrcpy/releases/download/v1.20/scrcpy-server-v1.20 : b20aee4951f99b060c4a44000ba94de973f9604758ef62beb253b371aad3df34
license    : Apache-2.0
component  : network.util
summary    : Display and control your Android device
description: |
    This application provides display and control of Android devices connected on USB (or over TCP/IP). It does not require any root access.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(libusb-1.0)
    - pkgconfig(sdl2)
rundeps    :
    - android-tools
setup      : |
    %meson_configure --buildtype release --strip -Dportable=false -Dprebuilt_server="$sources/scrcpy-server-v$version" -Db_lto=true
build      : |
    %ninja_build
install    : |
    %ninja_install
